// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC36IChOqaPLSySOZVoTXxpg68cqNRJtgM',
    appId: '1:37694562724:web:d0aee49fade4cb7896a131',
    messagingSenderId: '37694562724',
    projectId: 'filmbase-7848a',
    authDomain: 'filmbase-7848a.firebaseapp.com',
    storageBucket: 'filmbase-7848a.firebasestorage.app',
    measurementId: 'G-VHNP9DGV8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2uZFVn4_ekX2zjI3_1tl_G9XgXlPL7n8',
    appId: '1:37694562724:android:9c92fe269735304796a131',
    messagingSenderId: '37694562724',
    projectId: 'filmbase-7848a',
    storageBucket: 'filmbase-7848a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzelotJhMZ4zni_CjtkINttq8utbkU4mU',
    appId: '1:37694562724:ios:81b31edba8f34dbe96a131',
    messagingSenderId: '37694562724',
    projectId: 'filmbase-7848a',
    storageBucket: 'filmbase-7848a.firebasestorage.app',
    iosBundleId: 'com.example.filmbase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzelotJhMZ4zni_CjtkINttq8utbkU4mU',
    appId: '1:37694562724:ios:81b31edba8f34dbe96a131',
    messagingSenderId: '37694562724',
    projectId: 'filmbase-7848a',
    storageBucket: 'filmbase-7848a.firebasestorage.app',
    iosBundleId: 'com.example.filmbase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC36IChOqaPLSySOZVoTXxpg68cqNRJtgM',
    appId: '1:37694562724:web:d98d90bf897d331d96a131',
    messagingSenderId: '37694562724',
    projectId: 'filmbase-7848a',
    authDomain: 'filmbase-7848a.firebaseapp.com',
    storageBucket: 'filmbase-7848a.firebasestorage.app',
    measurementId: 'G-2816PRRD1Z',
  );
}
